apiVersion: apps/v1
kind: Deployment   #deployment控制副本
metadata:          #定义资源的元数据信息，比如名称、命名空间
  name: java-demo  #名称在同一个命名空间中必须唯一
spec:              #定义deploy副本的属性
  replicas: 1      #副本同时存在数量
  selector:
    matchLabels:   #定义匹配标签
      project: www
      app: java-demo
  template:
    metadata:
      labels:
        project: www
        app: java-demo
    spec:          #定义副本加载的容器的属性
      imagePullSecrets:
        - name: java-demo
      containers:
        - image: dennnys/pipeline:v1.1
          name: java-demo
          resources:  #资源
            requests:
              cpu: 0.5
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi

---
apiVersion: v1
kind: Service   #定义服务yaml文件
metadata:
  name: htmx-demo  #定义服务名称
spec:
  selector:
    project: www
    app: java-demo
  type: NodePort  #service的访问类型是nodeport
  ports:
    - port: 8080   #service监听8080端口
      nodePort: 31529   #转发的端口号是8080